package android.support.constraint;

import com.utebooks.app_utebooks.C0719R;

/* renamed from: android.support.constraint.R */
public final class C0003R {

    /* renamed from: android.support.constraint.R$attr */
    public static final class attr {
        public static final int constraintSet = 2130903136;
        public static final int layout_constraintBaseline_creator = 2130903217;
        public static final int layout_constraintBaseline_toBaselineOf = 2130903218;
        public static final int layout_constraintBottom_creator = 2130903219;
        public static final int layout_constraintBottom_toBottomOf = 2130903220;
        public static final int layout_constraintBottom_toTopOf = 2130903221;
        public static final int layout_constraintDimensionRatio = 2130903222;
        public static final int layout_constraintEnd_toEndOf = 2130903223;
        public static final int layout_constraintEnd_toStartOf = 2130903224;
        public static final int layout_constraintGuide_begin = 2130903225;
        public static final int layout_constraintGuide_end = 2130903226;
        public static final int layout_constraintGuide_percent = 2130903227;
        public static final int layout_constraintHeight_default = 2130903228;
        public static final int layout_constraintHeight_max = 2130903229;
        public static final int layout_constraintHeight_min = 2130903230;
        public static final int layout_constraintHorizontal_bias = 2130903231;
        public static final int layout_constraintHorizontal_chainStyle = 2130903232;
        public static final int layout_constraintHorizontal_weight = 2130903233;
        public static final int layout_constraintLeft_creator = 2130903234;
        public static final int layout_constraintLeft_toLeftOf = 2130903235;
        public static final int layout_constraintLeft_toRightOf = 2130903236;
        public static final int layout_constraintRight_creator = 2130903237;
        public static final int layout_constraintRight_toLeftOf = 2130903238;
        public static final int layout_constraintRight_toRightOf = 2130903239;
        public static final int layout_constraintStart_toEndOf = 2130903240;
        public static final int layout_constraintStart_toStartOf = 2130903241;
        public static final int layout_constraintTop_creator = 2130903242;
        public static final int layout_constraintTop_toBottomOf = 2130903243;
        public static final int layout_constraintTop_toTopOf = 2130903244;
        public static final int layout_constraintVertical_bias = 2130903245;
        public static final int layout_constraintVertical_chainStyle = 2130903246;
        public static final int layout_constraintVertical_weight = 2130903247;
        public static final int layout_constraintWidth_default = 2130903248;
        public static final int layout_constraintWidth_max = 2130903249;
        public static final int layout_constraintWidth_min = 2130903250;
        public static final int layout_editor_absoluteX = 2130903251;
        public static final int layout_editor_absoluteY = 2130903252;
        public static final int layout_goneMarginBottom = 2130903253;
        public static final int layout_goneMarginEnd = 2130903254;
        public static final int layout_goneMarginLeft = 2130903255;
        public static final int layout_goneMarginRight = 2130903256;
        public static final int layout_goneMarginStart = 2130903257;
        public static final int layout_goneMarginTop = 2130903258;
        public static final int layout_optimizationLevel = 2130903260;
    }

    /* renamed from: android.support.constraint.R$id */
    public static final class C0004id {
        public static final int all = 2131230819;
        public static final int basic = 2131230824;
        public static final int chains = 2131230839;
        public static final int none = 2131230926;
        public static final int packed = 2131230932;
        public static final int parent = 2131230934;
        public static final int spread = 2131230985;
        public static final int spread_inside = 2131230986;
        public static final int wrap = 2131231029;
    }

    /* renamed from: android.support.constraint.R$styleable */
    public static final class styleable {
        public static final int[] ConstraintLayout_Layout = {16842948, 16843039, 16843040, 16843071, 16843072, C0719R.attr.constraintSet, C0719R.attr.layout_constraintBaseline_creator, C0719R.attr.layout_constraintBaseline_toBaselineOf, C0719R.attr.layout_constraintBottom_creator, C0719R.attr.layout_constraintBottom_toBottomOf, C0719R.attr.layout_constraintBottom_toTopOf, C0719R.attr.layout_constraintDimensionRatio, C0719R.attr.layout_constraintEnd_toEndOf, C0719R.attr.layout_constraintEnd_toStartOf, C0719R.attr.layout_constraintGuide_begin, C0719R.attr.layout_constraintGuide_end, C0719R.attr.layout_constraintGuide_percent, C0719R.attr.layout_constraintHeight_default, C0719R.attr.layout_constraintHeight_max, C0719R.attr.layout_constraintHeight_min, C0719R.attr.layout_constraintHorizontal_bias, C0719R.attr.layout_constraintHorizontal_chainStyle, C0719R.attr.layout_constraintHorizontal_weight, C0719R.attr.layout_constraintLeft_creator, C0719R.attr.layout_constraintLeft_toLeftOf, C0719R.attr.layout_constraintLeft_toRightOf, C0719R.attr.layout_constraintRight_creator, C0719R.attr.layout_constraintRight_toLeftOf, C0719R.attr.layout_constraintRight_toRightOf, C0719R.attr.layout_constraintStart_toEndOf, C0719R.attr.layout_constraintStart_toStartOf, C0719R.attr.layout_constraintTop_creator, C0719R.attr.layout_constraintTop_toBottomOf, C0719R.attr.layout_constraintTop_toTopOf, C0719R.attr.layout_constraintVertical_bias, C0719R.attr.layout_constraintVertical_chainStyle, C0719R.attr.layout_constraintVertical_weight, C0719R.attr.layout_constraintWidth_default, C0719R.attr.layout_constraintWidth_max, C0719R.attr.layout_constraintWidth_min, C0719R.attr.layout_editor_absoluteX, C0719R.attr.layout_editor_absoluteY, C0719R.attr.layout_goneMarginBottom, C0719R.attr.layout_goneMarginEnd, C0719R.attr.layout_goneMarginLeft, C0719R.attr.layout_goneMarginRight, C0719R.attr.layout_goneMarginStart, C0719R.attr.layout_goneMarginTop, C0719R.attr.layout_optimizationLevel};
        public static final int ConstraintLayout_Layout_android_maxHeight = 2;
        public static final int ConstraintLayout_Layout_android_maxWidth = 1;
        public static final int ConstraintLayout_Layout_android_minHeight = 4;
        public static final int ConstraintLayout_Layout_android_minWidth = 3;
        public static final int ConstraintLayout_Layout_android_orientation = 0;
        public static final int ConstraintLayout_Layout_constraintSet = 5;
        public static final int ConstraintLayout_Layout_layout_constraintBaseline_creator = 6;
        public static final int ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf = 7;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_creator = 8;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_toBottomOf = 9;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_toTopOf = 10;
        public static final int ConstraintLayout_Layout_layout_constraintDimensionRatio = 11;
        public static final int ConstraintLayout_Layout_layout_constraintEnd_toEndOf = 12;
        public static final int ConstraintLayout_Layout_layout_constraintEnd_toStartOf = 13;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_begin = 14;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_end = 15;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_percent = 16;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_default = 17;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_max = 18;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_min = 19;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_bias = 20;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_chainStyle = 21;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_weight = 22;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_creator = 23;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_toLeftOf = 24;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_toRightOf = 25;
        public static final int ConstraintLayout_Layout_layout_constraintRight_creator = 26;
        public static final int ConstraintLayout_Layout_layout_constraintRight_toLeftOf = 27;
        public static final int ConstraintLayout_Layout_layout_constraintRight_toRightOf = 28;
        public static final int ConstraintLayout_Layout_layout_constraintStart_toEndOf = 29;
        public static final int ConstraintLayout_Layout_layout_constraintStart_toStartOf = 30;
        public static final int ConstraintLayout_Layout_layout_constraintTop_creator = 31;
        public static final int ConstraintLayout_Layout_layout_constraintTop_toBottomOf = 32;
        public static final int ConstraintLayout_Layout_layout_constraintTop_toTopOf = 33;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_bias = 34;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_chainStyle = 35;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_weight = 36;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_default = 37;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_max = 38;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_min = 39;
        public static final int ConstraintLayout_Layout_layout_editor_absoluteX = 40;
        public static final int ConstraintLayout_Layout_layout_editor_absoluteY = 41;
        public static final int ConstraintLayout_Layout_layout_goneMarginBottom = 42;
        public static final int ConstraintLayout_Layout_layout_goneMarginEnd = 43;
        public static final int ConstraintLayout_Layout_layout_goneMarginLeft = 44;
        public static final int ConstraintLayout_Layout_layout_goneMarginRight = 45;
        public static final int ConstraintLayout_Layout_layout_goneMarginStart = 46;
        public static final int ConstraintLayout_Layout_layout_goneMarginTop = 47;
        public static final int ConstraintLayout_Layout_layout_optimizationLevel = 48;
        public static final int[] ConstraintSet = {16842948, 16842960, 16842972, 16842996, 16842997, 16842999, 16843000, 16843001, 16843002, 16843551, 16843552, 16843553, 16843554, 16843555, 16843556, 16843557, 16843559, 16843560, 16843701, 16843702, 16843770, 16843840, C0719R.attr.layout_constraintBaseline_creator, C0719R.attr.layout_constraintBaseline_toBaselineOf, C0719R.attr.layout_constraintBottom_creator, C0719R.attr.layout_constraintBottom_toBottomOf, C0719R.attr.layout_constraintBottom_toTopOf, C0719R.attr.layout_constraintDimensionRatio, C0719R.attr.layout_constraintEnd_toEndOf, C0719R.attr.layout_constraintEnd_toStartOf, C0719R.attr.layout_constraintGuide_begin, C0719R.attr.layout_constraintGuide_end, C0719R.attr.layout_constraintGuide_percent, C0719R.attr.layout_constraintHeight_default, C0719R.attr.layout_constraintHeight_max, C0719R.attr.layout_constraintHeight_min, C0719R.attr.layout_constraintHorizontal_bias, C0719R.attr.layout_constraintHorizontal_chainStyle, C0719R.attr.layout_constraintHorizontal_weight, C0719R.attr.layout_constraintLeft_creator, C0719R.attr.layout_constraintLeft_toLeftOf, C0719R.attr.layout_constraintLeft_toRightOf, C0719R.attr.layout_constraintRight_creator, C0719R.attr.layout_constraintRight_toLeftOf, C0719R.attr.layout_constraintRight_toRightOf, C0719R.attr.layout_constraintStart_toEndOf, C0719R.attr.layout_constraintStart_toStartOf, C0719R.attr.layout_constraintTop_creator, C0719R.attr.layout_constraintTop_toBottomOf, C0719R.attr.layout_constraintTop_toTopOf, C0719R.attr.layout_constraintVertical_bias, C0719R.attr.layout_constraintVertical_chainStyle, C0719R.attr.layout_constraintVertical_weight, C0719R.attr.layout_constraintWidth_default, C0719R.attr.layout_constraintWidth_max, C0719R.attr.layout_constraintWidth_min, C0719R.attr.layout_editor_absoluteX, C0719R.attr.layout_editor_absoluteY, C0719R.attr.layout_goneMarginBottom, C0719R.attr.layout_goneMarginEnd, C0719R.attr.layout_goneMarginLeft, C0719R.attr.layout_goneMarginRight, C0719R.attr.layout_goneMarginStart, C0719R.attr.layout_goneMarginTop};
        public static final int ConstraintSet_android_alpha = 9;
        public static final int ConstraintSet_android_elevation = 21;
        public static final int ConstraintSet_android_id = 1;
        public static final int ConstraintSet_android_layout_height = 4;
        public static final int ConstraintSet_android_layout_marginBottom = 8;
        public static final int ConstraintSet_android_layout_marginEnd = 19;
        public static final int ConstraintSet_android_layout_marginLeft = 5;
        public static final int ConstraintSet_android_layout_marginRight = 7;
        public static final int ConstraintSet_android_layout_marginStart = 18;
        public static final int ConstraintSet_android_layout_marginTop = 6;
        public static final int ConstraintSet_android_layout_width = 3;
        public static final int ConstraintSet_android_orientation = 0;
        public static final int ConstraintSet_android_rotationX = 16;
        public static final int ConstraintSet_android_rotationY = 17;
        public static final int ConstraintSet_android_scaleX = 14;
        public static final int ConstraintSet_android_scaleY = 15;
        public static final int ConstraintSet_android_transformPivotX = 10;
        public static final int ConstraintSet_android_transformPivotY = 11;
        public static final int ConstraintSet_android_translationX = 12;
        public static final int ConstraintSet_android_translationY = 13;
        public static final int ConstraintSet_android_translationZ = 20;
        public static final int ConstraintSet_android_visibility = 2;
        public static final int ConstraintSet_layout_constraintBaseline_creator = 22;
        public static final int ConstraintSet_layout_constraintBaseline_toBaselineOf = 23;
        public static final int ConstraintSet_layout_constraintBottom_creator = 24;
        public static final int ConstraintSet_layout_constraintBottom_toBottomOf = 25;
        public static final int ConstraintSet_layout_constraintBottom_toTopOf = 26;
        public static final int ConstraintSet_layout_constraintDimensionRatio = 27;
        public static final int ConstraintSet_layout_constraintEnd_toEndOf = 28;
        public static final int ConstraintSet_layout_constraintEnd_toStartOf = 29;
        public static final int ConstraintSet_layout_constraintGuide_begin = 30;
        public static final int ConstraintSet_layout_constraintGuide_end = 31;
        public static final int ConstraintSet_layout_constraintGuide_percent = 32;
        public static final int ConstraintSet_layout_constraintHeight_default = 33;
        public static final int ConstraintSet_layout_constraintHeight_max = 34;
        public static final int ConstraintSet_layout_constraintHeight_min = 35;
        public static final int ConstraintSet_layout_constraintHorizontal_bias = 36;
        public static final int ConstraintSet_layout_constraintHorizontal_chainStyle = 37;
        public static final int ConstraintSet_layout_constraintHorizontal_weight = 38;
        public static final int ConstraintSet_layout_constraintLeft_creator = 39;
        public static final int ConstraintSet_layout_constraintLeft_toLeftOf = 40;
        public static final int ConstraintSet_layout_constraintLeft_toRightOf = 41;
        public static final int ConstraintSet_layout_constraintRight_creator = 42;
        public static final int ConstraintSet_layout_constraintRight_toLeftOf = 43;
        public static final int ConstraintSet_layout_constraintRight_toRightOf = 44;
        public static final int ConstraintSet_layout_constraintStart_toEndOf = 45;
        public static final int ConstraintSet_layout_constraintStart_toStartOf = 46;
        public static final int ConstraintSet_layout_constraintTop_creator = 47;
        public static final int ConstraintSet_layout_constraintTop_toBottomOf = 48;
        public static final int ConstraintSet_layout_constraintTop_toTopOf = 49;
        public static final int ConstraintSet_layout_constraintVertical_bias = 50;
        public static final int ConstraintSet_layout_constraintVertical_chainStyle = 51;
        public static final int ConstraintSet_layout_constraintVertical_weight = 52;
        public static final int ConstraintSet_layout_constraintWidth_default = 53;
        public static final int ConstraintSet_layout_constraintWidth_max = 54;
        public static final int ConstraintSet_layout_constraintWidth_min = 55;
        public static final int ConstraintSet_layout_editor_absoluteX = 56;
        public static final int ConstraintSet_layout_editor_absoluteY = 57;
        public static final int ConstraintSet_layout_goneMarginBottom = 58;
        public static final int ConstraintSet_layout_goneMarginEnd = 59;
        public static final int ConstraintSet_layout_goneMarginLeft = 60;
        public static final int ConstraintSet_layout_goneMarginRight = 61;
        public static final int ConstraintSet_layout_goneMarginStart = 62;
        public static final int ConstraintSet_layout_goneMarginTop = 63;
        public static final int[] LinearConstraintLayout = {16842948};
        public static final int LinearConstraintLayout_android_orientation = 0;
    }
}
